import type { PageServerLoad } from './$types';
import { createSupabaseAdminClient } from '$lib/server/supabase';

export const load: PageServerLoad = async () => {
	const admin = createSupabaseAdminClient();

	// Fetch all user preferences to see leaderboard opt-in status
	const { data: preferences } = await admin.from('user_preferences').select(`
			user_id,
			show_on_leaderboard,
			leaderboard_display_name,
			profiles!inner(name, email)
		`);

	// Fetch session counts per user
	const { data: sessions } = await admin
		.from('sessions')
		.select('user_id, id')
		.eq('archived', false);

	const sessionCounts = (sessions || []).reduce<Record<string, number>>((acc, s) => {
		acc[s.user_id] = (acc[s.user_id] || 0) + 1;
		return acc;
	}, {});

	const optedIn = (preferences || []).filter((p) => p.show_on_leaderboard);
	const optedOut = (preferences || []).filter((p) => !p.show_on_leaderboard);

	// Calculate stats
	const totalUsers = (preferences || []).length;
	const optInRate = totalUsers > 0 ? (optedIn.length / totalUsers) * 100 : 0;

	// Users with custom names
	const customNames = optedIn.filter((p) => p.leaderboard_display_name);

	// Recent opt-ins (last 7 days)
	const sevenDaysAgo = new Date();
	sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);

	// Top leaderboard participants by sessions
	const topParticipants = optedIn
		.map((p) => ({
			...p,
			session_count: sessionCounts[p.user_id] || 0
		}))
		.sort((a, b) => b.session_count - a.session_count)
		.slice(0, 10);

	return {
		stats: {
			totalUsers,
			optedIn: optedIn.length,
			optedOut: optedOut.length,
			optInRate: Math.round(optInRate),
			customNames: customNames.length,
			autoGenerated: optedIn.length - customNames.length
		},
		topParticipants,
		recentOptIns: optedIn.slice(0, 20),
		// Moderation isn't implemented yet — this is always empty, not a
		// "checked, none found" result. See the "Privacy Flags" tile in
		// +page.svelte for how this is labeled to avoid implying otherwise.
		flaggedDisplayNames: []
	};
};
