<script lang="ts">
	import type { PageData } from './$types';
	let { data }: { data: PageData } = $props();
</script>

<svelte:head>
	<title>Leaderboard Administration — Admin</title>
</svelte:head>

<div class="space-y-6">
	<!-- Header -->
	<div>
		<h2 class="text-lg font-bold text-[#f0ece4]">Leaderboard Administration</h2>
		<p class="text-sm text-[#9a8f7a] mt-0.5">
			Monitor participation, privacy compliance, and leaderboard health
		</p>
	</div>

	<!-- Key Stats -->
	<div class="grid grid-cols-2 lg:grid-cols-4 gap-4">
		{#each [
			{
				label: 'Total Users',
				value: data.stats.totalUsers,
				sub: 'registered',
				icon: 'M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z',
				color: '#9a8f7a'
			},
			{
				label: 'Opted In',
				value: data.stats.optedIn,
				sub: `${data.stats.optInRate}% of users`,
				icon: 'M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z',
				color: '#3de8c8'
			},
			{
				label: 'Custom Names',
				value: data.stats.customNames,
				sub: `${data.stats.autoGenerated} auto-generated`,
				icon: 'M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z',
				color: '#f5a623'
			},
			{
				label: 'Privacy Flags',
				value: data.flaggedDisplayNames.length,
				sub: 'for review',
				icon: 'M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z',
				color: data.flaggedDisplayNames.length > 0 ? '#ff4444' : '#3de8c8'
			}
		] as stat}
			<div class="bg-[#131010] border border-[#221c18] rounded-xl p-5">
				<div class="flex items-start justify-between mb-2">
					<p class="text-xs text-[#9a8f7a] uppercase tracking-wider">{stat.label}</p>
					<svg
						class="w-5 h-5 flex-shrink-0"
						style="color: {stat.color}"
						fill="none"
						stroke="currentColor"
						viewBox="0 0 24 24"
					>
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d={stat.icon} />
					</svg>
				</div>
				<p class="text-3xl font-bold" style="color: {stat.color}">{stat.value}</p>
				<p class="text-xs text-[#4a4038] mt-1">{stat.sub}</p>
			</div>
		{/each}
	</div>

	<!-- Top Participants & Recent Opt-ins -->
	<div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
		<!-- Top Participants -->
		<div class="bg-[#131010] border border-[#221c18] rounded-xl p-5">
			<h3 class="text-sm font-semibold text-[#f0ece4] mb-4">🏆 Top Leaderboard Participants</h3>
			{#if data.topParticipants.length === 0}
				<p class="text-sm text-[#4a4038] text-center py-8">No participants yet</p>
			{:else}
				<div class="space-y-2">
					{#each data.topParticipants as participant, i}
						<div class="flex items-center gap-3 p-3 rounded-lg bg-[#0a0809]">
							<div
								class="w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0"
								style="background-color: {i < 3 ? '#f5a623' : '#221c18'}20; border: 1px solid {i < 3 ? '#f5a623' : '#221c18'}40"
							>
								<span class="text-sm font-bold" style="color: {i < 3 ? '#f5a623' : '#9a8f7a'}">
									{i + 1}
								</span>
							</div>
							<div class="flex-1 min-w-0">
								<p class="text-sm font-medium text-[#f0ece4] truncate">
									{participant.leaderboard_display_name || 'Auto-generated'}
								</p>
								<p class="text-xs text-[#4a4038] truncate">
									{(participant.profiles as any)?.email || 'Unknown'}
								</p>
							</div>
							<div class="text-right flex-shrink-0">
								<p class="text-lg font-bold text-[#f5a623]">{participant.session_count}</p>
								<p class="text-xs text-[#4a4038]">sessions</p>
							</div>
						</div>
					{/each}
				</div>
			{/if}
		</div>

		<!-- Participation Trends -->
		<div class="bg-[#131010] border border-[#221c18] rounded-xl p-5">
			<h3 class="text-sm font-semibold text-[#f0ece4] mb-4">📈 Participation Metrics</h3>
			<div class="space-y-4">
				<div class="p-4 bg-[#0a0809] rounded-lg">
					<div class="flex items-center justify-between mb-2">
						<span class="text-sm text-[#9a8f7a]">Opt-in Rate</span>
						<span class="text-2xl font-bold text-[#3de8c8]">{data.stats.optInRate}%</span>
					</div>
					<div class="w-full bg-[#221c18] rounded-full h-2">
						<div
							class="bg-[#3de8c8] h-2 rounded-full transition-all"
							style="width: {data.stats.optInRate}%"
						></div>
					</div>
					<p class="text-xs text-[#4a4038] mt-2">
						{data.stats.optedIn} opted in, {data.stats.optedOut} opted out
					</p>
				</div>

				<div class="p-4 bg-[#0a0809] rounded-lg">
					<div class="flex items-center justify-between mb-2">
						<span class="text-sm text-[#9a8f7a]">Custom Names</span>
						<span class="text-2xl font-bold text-[#f5a623]">{data.stats.customNames}</span>
					</div>
					<div class="w-full bg-[#221c18] rounded-full h-2">
						<div
							class="bg-[#f5a623] h-2 rounded-full transition-all"
							style="width: {data.stats.optedIn > 0 ? (data.stats.customNames / data.stats.optedIn) * 100 : 0}%"
						></div>
					</div>
					<p class="text-xs text-[#4a4038] mt-2">
						{data.stats.autoGenerated} users using auto-generated names
					</p>
				</div>

				<div class="p-4 bg-[#0a0809] rounded-lg">
					<p class="text-sm font-medium text-[#f0ece4] mb-1">Privacy Compliance</p>
					<p class="text-xs text-[#9a8f7a]">
						✓ All participants opted in voluntarily<br />
						✓ Display names anonymized<br />
						✓ GDPR compliant
					</p>
				</div>
			</div>
		</div>
	</div>

	<!-- Information Panel -->
	<div class="bg-[#131010] border border-[#f5a623]/20 rounded-xl p-6">
		<div class="flex items-start gap-3">
			<svg
				class="w-6 h-6 text-[#f5a623] flex-shrink-0 mt-0.5"
				fill="none"
				stroke="currentColor"
				viewBox="0 0 24 24"
			>
				<path
					stroke-linecap="round"
					stroke-linejoin="round"
					stroke-width="2"
					d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
				/>
			</svg>
			<div class="flex-1">
				<h3 class="text-sm font-semibold text-[#f0ece4] mb-2">Leaderboard Features</h3>
				<p class="text-sm text-[#9a8f7a] mb-3">
					The leaderboard system provides privacy-preserving competitive features with full user
					control.
				</p>
				<div class="grid grid-cols-1 md:grid-cols-2 gap-3">
					<div class="p-3 bg-[#0a0809] rounded-lg">
						<p class="text-sm font-medium text-[#f0ece4] mb-1">✓ Opt-in System</p>
						<p class="text-xs text-[#9a8f7a]">Users choose to participate, instant opt-out</p>
					</div>
					<div class="p-3 bg-[#0a0809] rounded-lg">
						<p class="text-sm font-medium text-[#f0ece4] mb-1">✓ Privacy Protection</p>
						<p class="text-xs text-[#9a8f7a]">Anonymous display names, no personal data</p>
					</div>
					<div class="p-3 bg-[#0a0809] rounded-lg">
						<p class="text-sm font-medium text-[#f0ece4] mb-1">✓ Fair Categories</p>
						<p class="text-xs text-[#9a8f7a]">Age groups and experience levels for comparison</p>
					</div>
					<div class="p-3 bg-[#0a0809] rounded-lg">
						<p class="text-sm font-medium text-[#f0ece4] mb-1">✓ Moderation</p>
						<p class="text-xs text-[#9a8f7a]">Display name review and flagging system</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
