<script lang="ts">
	import type { PageData } from './$types';
	let { data }: { data: PageData } = $props();
</script>

<svelte:head>
	<title>Leaderboard Administration — Admin</title>
</svelte:head>

<div class="space-y-6">
	<!-- Header -->
	<div>
		<h2 class="text-lg font-bold text-[#f0ece4]">Leaderboard Administration</h2>
		<p class="mt-0.5 text-sm text-[#9a8f7a]">
			Monitor participation, privacy controls, and leaderboard health
		</p>
	</div>

	<!-- Key Stats -->
	<div class="grid grid-cols-2 gap-4 lg:grid-cols-4">
		{#each [{ label: 'Total Users', value: data.stats.totalUsers, sub: 'registered', icon: 'M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z', color: '#9a8f7a' }, { label: 'Opted In', value: data.stats.optedIn, sub: `${data.stats.optInRate}% of users`, icon: 'M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z', color: '#3de8c8' }, { label: 'Custom Names', value: data.stats.customNames, sub: `${data.stats.autoGenerated} auto-generated`, icon: 'M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7-7z', color: '#f5a623' }, { label: 'Privacy Flags', value: data.flaggedDisplayNames.length, sub: 'moderation not yet implemented', icon: 'M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z', color: '#9a8f7a' }] as stat}
			<div class="rounded-xl border border-[#221c18] bg-[#131010] p-5">
				<div class="mb-2 flex items-start justify-between">
					<p class="text-xs tracking-wider text-[#9a8f7a] uppercase">{stat.label}</p>
					<svg
						class="h-5 w-5 flex-shrink-0"
						style="color: {stat.color}"
						fill="none"
						stroke="currentColor"
						viewBox="0 0 24 24"
					>
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d={stat.icon} />
					</svg>
				</div>
				<p class="text-3xl font-bold" style="color: {stat.color}">{stat.value}</p>
				<p class="mt-1 text-xs text-[#4a4038]">{stat.sub}</p>
			</div>
		{/each}
	</div>

	<!-- Top Participants & Recent Opt-ins -->
	<div class="grid grid-cols-1 gap-6 lg:grid-cols-2">
		<!-- Top Participants -->
		<div class="rounded-xl border border-[#221c18] bg-[#131010] p-5">
			<h3 class="mb-4 text-sm font-semibold text-[#f0ece4]">🏆 Top Leaderboard Participants</h3>
			{#if data.topParticipants.length === 0}
				<p class="py-8 text-center text-sm text-[#4a4038]">No participants yet</p>
			{:else}
				<div class="space-y-2">
					{#each data.topParticipants as participant, i}
						<div class="flex items-center gap-3 rounded-lg bg-[#0a0809] p-3">
							<div
								class="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-full"
								style="background-color: {i < 3 ? '#f5a623' : '#221c18'}20; border: 1px solid {i < 3
									? '#f5a623'
									: '#221c18'}40"
							>
								<span class="text-sm font-bold" style="color: {i < 3 ? '#f5a623' : '#9a8f7a'}">
									{i + 1}
								</span>
							</div>
							<div class="min-w-0 flex-1">
								<p class="truncate text-sm font-medium text-[#f0ece4]">
									{participant.leaderboard_display_name || 'Auto-generated'}
								</p>
								<p class="truncate text-xs text-[#4a4038]">
									{(participant.profiles as any)?.email || 'Unknown'}
								</p>
							</div>
							<div class="flex-shrink-0 text-right">
								<p class="text-lg font-bold text-[#f5a623]">{participant.session_count}</p>
								<p class="text-xs text-[#4a4038]">sessions</p>
							</div>
						</div>
					{/each}
				</div>
			{/if}
		</div>

		<!-- Participation Trends -->
		<div class="rounded-xl border border-[#221c18] bg-[#131010] p-5">
			<h3 class="mb-4 text-sm font-semibold text-[#f0ece4]">📈 Participation Metrics</h3>
			<div class="space-y-4">
				<div class="rounded-lg bg-[#0a0809] p-4">
					<div class="mb-2 flex items-center justify-between">
						<span class="text-sm text-[#9a8f7a]">Opt-in Rate</span>
						<span class="text-2xl font-bold text-[#3de8c8]">{data.stats.optInRate}%</span>
					</div>
					<div class="h-2 w-full rounded-full bg-[#221c18]">
						<div
							class="h-2 rounded-full bg-[#3de8c8] transition-all"
							style="width: {data.stats.optInRate}%"
						></div>
					</div>
					<p class="mt-2 text-xs text-[#4a4038]">
						{data.stats.optedIn} opted in, {data.stats.optedOut} opted out
					</p>
				</div>

				<div class="rounded-lg bg-[#0a0809] p-4">
					<div class="mb-2 flex items-center justify-between">
						<span class="text-sm text-[#9a8f7a]">Custom Names</span>
						<span class="text-2xl font-bold text-[#f5a623]">{data.stats.customNames}</span>
					</div>
					<div class="h-2 w-full rounded-full bg-[#221c18]">
						<div
							class="h-2 rounded-full bg-[#f5a623] transition-all"
							style="width: {data.stats.optedIn > 0
								? (data.stats.customNames / data.stats.optedIn) * 100
								: 0}%"
						></div>
					</div>
					<p class="mt-2 text-xs text-[#4a4038]">
						{data.stats.autoGenerated} users using auto-generated names
					</p>
				</div>

				<div class="rounded-lg bg-[#0a0809] p-4">
					<p class="mb-1 text-sm font-medium text-[#f0ece4]">Privacy Controls</p>
					<p class="text-xs text-[#9a8f7a]">
						✓ Participation is opt-in<br />
						✓ Public ranking uses display names instead of account emails<br />
						• Name moderation and flagging are not implemented yet
					</p>
				</div>
			</div>
		</div>
	</div>

	<!-- Information Panel -->
	<div class="rounded-xl border border-[#f5a623]/20 bg-[#131010] p-6">
		<div class="flex items-start gap-3">
			<svg
				class="mt-0.5 h-6 w-6 flex-shrink-0 text-[#f5a623]"
				fill="none"
				stroke="currentColor"
				viewBox="0 0 24 24"
			>
				<path
					stroke-linecap="round"
					stroke-linejoin="round"
					stroke-width="2"
					d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
				/>
			</svg>
			<div class="flex-1">
				<h3 class="mb-2 text-sm font-semibold text-[#f0ece4]">Leaderboard Features</h3>
				<p class="mb-3 text-sm text-[#9a8f7a]">
					The leaderboard system provides privacy-aware competitive features with user-controlled
					participation.
				</p>
				<div class="grid grid-cols-1 gap-3 md:grid-cols-2">
					<div class="rounded-lg bg-[#0a0809] p-3">
						<p class="mb-1 text-sm font-medium text-[#f0ece4]">✓ Opt-in System</p>
						<p class="text-xs text-[#9a8f7a]">Users choose to participate, instant opt-out</p>
					</div>
					<div class="rounded-lg bg-[#0a0809] p-3">
						<p class="mb-1 text-sm font-medium text-[#f0ece4]">✓ Privacy Protection</p>
						<p class="text-xs text-[#9a8f7a]">Public ranking does not expose account email addresses</p>
					</div>
					<div class="rounded-lg bg-[#0a0809] p-3">
						<p class="mb-1 text-sm font-medium text-[#f0ece4]">✓ All-time Competition</p>
						<p class="text-xs text-[#9a8f7a]">Competitive ranking is all-time; peer benchmarking is separate on Compare</p>
					</div>
					<div class="rounded-lg bg-[#0a0809] p-3">
						<p class="mb-1 text-sm font-medium text-[#f0ece4]">Moderation Status</p>
						<p class="text-xs text-[#9a8f7a]">Display-name review and flagging are not implemented yet</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
