#!/usr/bin/env python3
"""
AppGatePro Analytics — Documentation Generator
===============================================
Converts markdown chapter files into a TypeScript content module
for the SvelteKit docs route.

Usage:
    python3 scripts/generate-docs.py

Requirements:
    pip install markdown

Workflow:
    1. Edit chapter files in docs/chapters/
    2. Run this script
    3. Commit the updated src/lib/docs/content.ts

Adding a new chapter:
    1. Create docs/chapters/my-chapter.md
    2. Add an entry to CHAPTERS below
    3. Re-run this script
    4. Add a link to Sidebar.svelte if needed

Adding screenshots:
    Use standard markdown image syntax in chapter files:
        ![Alt text](https://your-cdn.com/docs/image.png)

Adding video embeds:
    Use an HTML block directly in the markdown:
        <div class="doc-video">
          <iframe src="https://www.youtube.com/embed/VIDEO_ID"
                  title="Description" allowfullscreen></iframe>
        </div>

    The .doc-video class is styled in [chapter]/+page.svelte prose CSS.
"""

import os
import sys
import json
import re
import textwrap
from pathlib import Path
from datetime import datetime

# ── Configuration ──────────────────────────────────────────────────────────────

# Root of the SvelteKit project (script lives in scripts/, project root is parent)
PROJECT_ROOT = Path(__file__).parent.parent

# Where chapter markdown files live
CHAPTERS_DIR = PROJECT_ROOT / 'docs' / 'chapters'

# Where the generated TypeScript file goes
OUTPUT_FILE = PROJECT_ROOT / 'src' / 'lib' / 'docs' / 'content.ts'

# Chapter definitions — order matters (determines sidebar order and prev/next nav)
# Format: (slug, title, description, icon, filename)
CHAPTERS = [
    (
        'session',
        'Your Session Data',
        'Understanding your runs, charts, technique scores, and three-page layout',
        '📊',
        'session.md',
    ),
    (
        'analytics',
        'Analytics & Trends',
        'Cross-session patterns, trend charts, and performance intelligence',
        '📈',
        'analytics.md',
    ),
    (
        'goals',
        'Training Goals',
        'Setting targets, predictions, health monitoring, and adaptive suggestions',
        '🎯',
        'goals.md',
    ),
    (
        'upload',
        'Uploading Sessions',
        'Getting your data in, error messages, and what happens during processing',
        '⬆️',
        'upload.md',
    ),
    (
        'profile',
        'Profile & Bike Setup',
        'Why profile data matters and what each field unlocks',
        '👤',
        'profile.md',
    ),
    (
        'reports',
        'Reports',
        'Session and progress reports, detail levels, and sharing with coaches',
        '📄',
        'reports.md',
    ),
    (
        'leaderboard',
        'Leaderboards & Benchmarking',
        'How ranking works, privacy controls, and using it well',
        '🏆',
        'leaderboard.md',
    ),
    (
        'help',
        'Help & Troubleshooting',
        'Common problems, upload errors, account issues, and bug reporting',
        '❓',
        'help.md',
    ),
]

# ── Markdown conversion ────────────────────────────────────────────────────────

def convert_markdown(text: str) -> str:
    """Convert markdown to HTML using the markdown library."""
    try:
        import markdown
    except ImportError:
        print('ERROR: markdown library not installed.')
        print('Run: pip install markdown')
        sys.exit(1)

    md = markdown.Markdown(extensions=['toc', 'fenced_code', 'tables'])
    return md.convert(text)


def strip_h1(text: str) -> str:
    """Remove the leading H1 title — rendered separately in the Svelte template."""
    return re.sub(r'^# .+\n', '', text, count=1)


def build_plain_text(html: str, max_chars: int = 4000) -> str:
    """Strip HTML tags to produce plain text for search indexing."""
    plain = re.sub(r'<[^>]+>', ' ', html)
    plain = re.sub(r'\s+', ' ', plain).strip()
    return plain[:max_chars]


# ── TypeScript generation ──────────────────────────────────────────────────────

def escape_template_literal(s: str) -> str:
    """Escape characters that would break a JS template literal."""
    s = s.replace('\\', '\\\\')
    s = s.replace('`', '\\`')
    s = s.replace('${', '\\${')
    return s


def generate_typescript(chapters_data: list[dict]) -> str:
    """Generate the full content.ts file content."""
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M')

    lines = [
        f'// Auto-generated by scripts/generate-docs.py — {timestamp}',
        '// Do not edit this file directly.',
        '// Edit the markdown files in docs/chapters/ and re-run the script.',
        '',
        'export interface DocChapter {',
        '  slug: string;',
        '  title: string;',
        '  desc: string;',
        '  icon: string;',
        '  html: string;',
        '  plain: string;',
        '}',
        '',
        'export const chapters: DocChapter[] = [',
    ]

    for ch in chapters_data:
        html_escaped  = escape_template_literal(ch['html'])
        plain_escaped = escape_template_literal(ch['plain'])
        lines += [
            '  {',
            f'    slug:  {json.dumps(ch["slug"])},',
            f'    title: {json.dumps(ch["title"])},',
            f'    desc:  {json.dumps(ch["desc"])},',
            f'    icon:  {json.dumps(ch["icon"])},',
            f'    html:  `{html_escaped}`,',
            f'    plain: `{plain_escaped}`,',
            '  },',
        ]

    lines += [
        '];',
        '',
        '// Convenience lookups',
        'export const chapterMap = new Map(chapters.map(c => [c.slug, c]));',
        'export const slugs = chapters.map(c => c.slug);',
        '',
    ]

    return '\n'.join(lines)


# ── Main ───────────────────────────────────────────────────────────────────────

def main() -> None:
    print('AppGatePro Docs Generator')
    print('─' * 40)

    # Check chapters directory exists
    if not CHAPTERS_DIR.exists():
        print(f'ERROR: Chapters directory not found: {CHAPTERS_DIR}')
        print(f'Create it and add your .md files there.')
        sys.exit(1)

    # Process each chapter
    chapters_data = []
    errors = []

    for slug, title, desc, icon, filename in CHAPTERS:
        path = CHAPTERS_DIR / filename

        if not path.exists():
            errors.append(f'  MISSING: {path}')
            continue

        text = path.read_text(encoding='utf-8')
        text = strip_h1(text)
        html  = convert_markdown(text)
        plain = build_plain_text(html)

        chapters_data.append({
            'slug':  slug,
            'title': title,
            'desc':  desc,
            'icon':  icon,
            'html':  html,
            'plain': plain,
        })

        size_kb = len(html) / 1024
        print(f'  ✓ {slug:<15} {title:<35} ({size_kb:.1f}KB)')

    if errors:
        print()
        print('WARNINGS — missing files:')
        for e in errors:
            print(e)
        print()
        if not chapters_data:
            print('ERROR: No chapters processed. Aborting.')
            sys.exit(1)

    # Ensure output directory exists
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)

    # Generate and write TypeScript
    ts = generate_typescript(chapters_data)
    OUTPUT_FILE.write_text(ts, encoding='utf-8')

    total_kb = OUTPUT_FILE.stat().st_size / 1024
    print()
    print(f'✓ Written: {OUTPUT_FILE}')
    print(f'  {len(chapters_data)} chapters · {total_kb:.0f}KB total')
    print()
    print('Done. Rebuild your SvelteKit app to pick up the changes.')


if __name__ == '__main__':
    main()
